phi3m:
  model_name: microsoft/Phi-3-mini-4k-instruct
  apis:
    - addr: http://<your-host>:8001/v1
      api_key: <your-api-key>
    - addr: http://<your-host>:8002/v1
      api_key: <your-api-key>
phi4m:
  model_name: microsoft/Phi-4-mini-instruct
  apis:
    - addr: http://<your-host>:8001/v1
      api_key: <your-api-key>
    - addr: http://<your-host>:8002/v1
      api_key: <your-api-key>
llama3.2-1b-inst:
  model_name: meta-llama/Llama-3.2-1B-Instruct
  apis:
    - addr: http://<your-host>:8001/v1
      api_key: <your-api-key>
    - addr: http://<your-host>:8002/v1
      api_key: <your-api-key>
qwen:
  model_name: Qwen/Qwen2.5-Coder-3B-Instruct
  apis:
    - addr: http://<your-host>:8001/v1
      api_key: <your-api-key>
    - addr: http://<your-host>:8002/v1
      api_key: <your-api-key>
codegemma:
  model_name: google/codegemma-7b-it
  apis:
    - addr: http://<your-host>:8001/v1
      api_key: <your-api-key>
    - addr: http://<your-host>:8002/v1
      api_key: <your-api-key>
ministral:
  model_name: mistralai/Ministral-8B-Instruct-2410
  apis:
    - addr: http://<your-host>:8001/v1
      api_key: <your-api-key>
    - addr: http://<your-host>:8002/v1
      api_key: <your-api-key>
